export const PERMISSIONS = {
  // Assignments
  CREATE_ASSIGNMENT: 'CREATE_ASSIGNMENT',
  EDIT_ASSIGNMENT: 'EDIT_ASSIGNMENT',
  DELETE_ASSIGNMENT: 'DELETE_ASSIGNMENT',
  VIEW_ASSIGNMENT: 'VIEW_ASSIGNMENT', // Added for completeness

  // Papers
  GENERATE_PAPER: 'GENERATE_PAPER',
  VIEW_PAPER: 'VIEW_PAPER',

  // Workflow (Review)
  SUBMIT_FOR_APPROVAL: 'SUBMIT_FOR_APPROVAL',
  APPROVE_PAPER: 'APPROVE_PAPER',
  REJECT_PAPER: 'REJECT_PAPER',
  PUBLISH_PAPER: 'PUBLISH_PAPER',

  // Analytics
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_INSTITUTION_ANALYTICS: 'VIEW_INSTITUTION_ANALYTICS',

  // Users & Groups
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_GROUPS: 'MANAGE_GROUPS',
  VIEW_ROSTER: 'VIEW_ROSTER',

  // Students (Assessments)
  ATTEMPT_ASSESSMENT: 'ATTEMPT_ASSESSMENT',
  SUBMIT_ASSESSMENT: 'SUBMIT_ASSESSMENT',
  VIEW_RESULTS: 'VIEW_RESULTS',

  // Grading
  GRADE_ASSESSMENT: 'GRADE_ASSESSMENT',
  PUBLISH_RESULTS: 'PUBLISH_RESULTS',

  // Question Bank
  MANAGE_QUESTION_BANK: 'MANAGE_QUESTION_BANK',

  // Syllabus
  MANAGE_SYLLABUS: 'MANAGE_SYLLABUS',

  // Audit
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

  // System
  MANAGE_SYSTEM: 'MANAGE_SYSTEM', // Super admin
} as const;

export type Permission = keyof typeof PERMISSIONS;
