import { PERMISSIONS, Permission } from './permissions';

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.MANAGE_SYSTEM,
    PERMISSIONS.CREATE_ASSIGNMENT,
    PERMISSIONS.EDIT_ASSIGNMENT,
    PERMISSIONS.DELETE_ASSIGNMENT,
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.GENERATE_PAPER,
    PERMISSIONS.VIEW_PAPER,
    PERMISSIONS.SUBMIT_FOR_APPROVAL,
    PERMISSIONS.APPROVE_PAPER,
    PERMISSIONS.REJECT_PAPER,
    PERMISSIONS.PUBLISH_PAPER,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_ORGANIZATION_ANALYTICS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_GROUPS,
    PERMISSIONS.VIEW_ROSTER,
    PERMISSIONS.GRADE_ASSESSMENT,
    PERMISSIONS.PUBLISH_RESULTS,
    PERMISSIONS.MANAGE_QUESTION_BANK,
    PERMISSIONS.MANAGE_SYLLABUS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  ADMIN: [
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.VIEW_PAPER,
    PERMISSIONS.APPROVE_PAPER,
    PERMISSIONS.REJECT_PAPER,
    PERMISSIONS.PUBLISH_PAPER,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_ORGANIZATION_ANALYTICS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_GROUPS,
    PERMISSIONS.VIEW_ROSTER,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_QUESTION_BANK,
  ],
  TEACHER: [
    PERMISSIONS.CREATE_ASSIGNMENT,
    PERMISSIONS.EDIT_ASSIGNMENT,
    PERMISSIONS.DELETE_ASSIGNMENT,
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.GENERATE_PAPER,
    PERMISSIONS.VIEW_PAPER,
    PERMISSIONS.SUBMIT_FOR_APPROVAL,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_ROSTER,
    PERMISSIONS.GRADE_ASSESSMENT,
    PERMISSIONS.PUBLISH_RESULTS,
    PERMISSIONS.MANAGE_QUESTION_BANK,
    PERMISSIONS.MANAGE_SYLLABUS,
  ],
  FACULTY: [
    PERMISSIONS.CREATE_ASSIGNMENT,
    PERMISSIONS.EDIT_ASSIGNMENT,
    PERMISSIONS.DELETE_ASSIGNMENT,
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.GENERATE_PAPER,
    PERMISSIONS.VIEW_PAPER,
    PERMISSIONS.SUBMIT_FOR_APPROVAL,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_ROSTER,
    PERMISSIONS.GRADE_ASSESSMENT,
    PERMISSIONS.PUBLISH_RESULTS,
    PERMISSIONS.MANAGE_QUESTION_BANK,
    PERMISSIONS.MANAGE_SYLLABUS,
  ],
  STUDENT: [
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.VIEW_PAPER,
    PERMISSIONS.ATTEMPT_ASSESSMENT,
    PERMISSIONS.SUBMIT_ASSESSMENT,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.GENERATE_PAPER,
  ],
};

export const hasPermission = (role: string, permission: Permission): boolean => {
  let normalizedRole = role;
  if (role === 'FACULTY') normalizedRole = 'TEACHER';
  if (role === 'ORG_ADMIN') normalizedRole = 'ADMIN';
  
  if (normalizedRole === 'SUPER_ADMIN') return true;
  const permissions = ROLE_PERMISSIONS[normalizedRole] ?? ROLE_PERMISSIONS[role];
  if (!permissions) return false;
  return permissions.includes(permission);
};
