'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { 
  Users, 
  FileText, 
  PieChart as ChartIcon, 
  BrainCircuit, 
  Building2, 
  TrendingUp,
  ChevronRight,
  ShieldCheck
} from 'lucide-react';
import Link from 'next/link';

interface DashboardStats {
  totals: {
    users: number;
    activeUsers: number;
    papersGenerated: number;
    assignmentsCreated: number;
  };
  aiAnalytics: {
    totalTokens: number;
    totalCost: number;
    providerUsage: Record<string, { tokens: number; cost: number }>;
  };
  departmentPerformance: Array<{
    departmentId: string;
    name: string;
    papersCount: number;
    averageScore: number;
  }>;
}

export default function AdminDashboard() {
  const [data, setData] = useState<DashboardStats | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadDashboard() {
      try {
        const res = await api.get('/admin/analytics');
        if (res.data?.success) {
          setData(res.data.data);
        }
      } catch (err) {
        console.error('Failed to load admin analytics:', err);
      } finally {
        setLoading(false);
      }
    }
    loadDashboard();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="w-8 h-8 border-4 border-blue-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  const totals = data?.totals || { users: 0, activeUsers: 0, papersGenerated: 0, assignmentsCreated: 0 };
  const aiStats = data?.aiAnalytics || { totalTokens: 0, totalCost: 0, providerUsage: {} };

  return (
    <div className="space-y-6">
      {/* Title & Badge */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl md:text-2xl font-bold text-gray-900">System Overview</h2>
          <p className="text-gray-500 text-xs md:text-sm">Real-time command center telemetry and status tracking.</p>
        </div>
        <div className="flex items-center gap-2 bg-green-50 border border-green-200 text-green-700 px-3 py-1.5 rounded-xl text-xs font-semibold w-fit">
          <ShieldCheck size={16} />
          <span>All Core Services Operational</span>
        </div>
      </div>

      {/* KPI Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
          <div>
            <span className="text-gray-400 text-xs font-semibold uppercase tracking-wider">Total Users</span>
            <h3 className="text-2xl font-bold text-gray-900 mt-1">{totals.users}</h3>
            <span className="text-[10px] text-green-500 font-bold flex items-center gap-0.5 mt-0.5">
              <TrendingUp size={10} /> Active: {totals.activeUsers}
            </span>
          </div>
          <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center">
            <Users size={22} />
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
          <div>
            <span className="text-gray-400 text-xs font-semibold uppercase tracking-wider">Paper Library</span>
            <h3 className="text-2xl font-bold text-gray-900 mt-1">{totals.papersGenerated}</h3>
            <span className="text-[10px] text-blue-500 font-medium mt-0.5 block">Generated by LLM</span>
          </div>
          <div className="w-12 h-12 bg-orange-50 text-orange-600 rounded-xl flex items-center justify-center">
            <FileText size={22} />
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
          <div>
            <span className="text-gray-400 text-xs font-semibold uppercase tracking-wider">Total Cost</span>
            <h3 className="text-2xl font-bold text-gray-900 mt-1">${aiStats.totalCost.toFixed(2)}</h3>
            <span className="text-[10px] text-gray-500 font-medium mt-0.5 block">
              {(aiStats.totalTokens / 1000).toFixed(0)}k Tokens used
            </span>
          </div>
          <div className="w-12 h-12 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center">
            <ChartIcon size={22} />
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
          <div>
            <span className="text-gray-400 text-xs font-semibold uppercase tracking-wider">Assignments</span>
            <h3 className="text-2xl font-bold text-gray-900 mt-1">{totals.assignmentsCreated}</h3>
            <span className="text-[10px] text-purple-500 font-medium mt-0.5 block">Classes & Groups</span>
          </div>
          <div className="w-12 h-12 bg-purple-50 text-purple-600 rounded-xl flex items-center justify-center">
            <BrainCircuit size={22} />
          </div>
        </div>
      </div>

      {/* Main content grid: Chart + Department performance */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Cost & Token Analytics Column */}
        <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm lg:col-span-1 space-y-6">
          <div>
            <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider">AI API Token Expense</h3>
            <p className="text-gray-400 text-[10px]">Percentage distribution of tokens processed per model vendor.</p>
          </div>

          <div className="space-y-4">
            {Object.entries(aiStats.providerUsage).map(([provider, details]) => {
              const percentage = aiStats.totalTokens > 0 
                ? (details.tokens / aiStats.totalTokens) * 100 
                : 0;
              
              const colorMap: Record<string, string> = {
                openai: 'bg-emerald-500',
                anthropic: 'bg-orange-500',
                gemini: 'bg-blue-500',
                nvidia: 'bg-lime-500',
                groq: 'bg-purple-500'
              };

              return (
                <div key={provider} className="space-y-1">
                  <div className="flex items-center justify-between text-xs font-medium">
                    <span className="capitalize">{provider}</span>
                    <span className="text-gray-500">{percentage.toFixed(1)}% (${details.cost.toFixed(2)})</span>
                  </div>
                  <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
                    <div 
                      className={`${colorMap[provider] || 'bg-gray-500'} h-full rounded-full transition-all duration-500`}
                      style={{ width: `${percentage}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>

          <Link href="/admin/analytics" className="inline-flex items-center gap-1.5 text-xs text-blue-600 hover:text-blue-700 font-semibold pt-2">
            View Extended Analytics
            <ChevronRight size={14} />
          </Link>
        </div>

        {/* Department performance Table Grid */}
        <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm lg:col-span-2 space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider">Department Telemetry</h3>
              <p className="text-gray-400 text-[10px]">Academic papers generated and student results average per department.</p>
            </div>
            <Link href="/admin/departments" className="p-2 hover:bg-gray-50 rounded-lg text-gray-400 hover:text-gray-600">
              <Building2 size={18} />
            </Link>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-medium text-gray-600 border-collapse">
              <thead>
                <tr className="border-b border-gray-100 text-gray-400 font-semibold uppercase tracking-wider">
                  <th className="py-2.5">Department Name</th>
                  <th className="py-2.5 text-center">Papers Generated</th>
                  <th className="py-2.5 text-center">Student Performance</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {data?.departmentPerformance.map((dept) => (
                  <tr key={dept.departmentId} className="hover:bg-gray-50/50 transition-colors">
                    <td className="py-3 font-semibold text-gray-800 flex items-center gap-2">
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                      {dept.name}
                    </td>
                    <td className="py-3 text-center font-bold text-gray-700">{dept.papersCount}</td>
                    <td className="py-3 text-center">
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                        dept.averageScore >= 80 
                          ? 'bg-green-50 text-green-700 border border-green-200' 
                          : 'bg-amber-50 text-amber-700 border border-amber-200'
                      }`}>
                        {dept.averageScore}% Avg
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  );
}
