import path from 'path';
import fs from 'fs/promises';
import type { IGeneratedPaper } from '../models/GeneratedPaper.model';
import { logger } from '../utils/logger';

export async function generatePdf(paper: IGeneratedPaper): Promise<{ pdfPath: string; pdfUrl: string }> {
  // Dynamic import to avoid loading Puppeteer at startup
  const puppeteer = await import('puppeteer-core');

  const html = buildPaperHtml(paper);

  const pdfDir = path.join(process.cwd(), 'uploads', 'pdfs');
  await fs.mkdir(pdfDir, { recursive: true });

  const fileName = `paper-${paper.assignmentId.toString()}-${Date.now()}.pdf`;
  const pdfPath = path.join(pdfDir, fileName);

  let browser;
  try {
    // Try to use system Chrome, fall back to puppeteer-bundled
    const executablePath = process.env.CHROMIUM_PATH ||
      (process.env.NODE_ENV === 'production'
        ? await import('@sparticuz/chromium').then((m) => m.default.executablePath())
        : undefined);

    browser = await puppeteer.default.launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
      executablePath: typeof executablePath === 'string' ? executablePath : undefined,
      headless: true,
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    await page.pdf({
      path: pdfPath,
      format: 'A4',
      margin: { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' },
      printBackground: true,
    });

    logger.info(`PDF generated: ${fileName}`);
    const pdfUrl = `/api/papers/download/${fileName}`;
    return { pdfPath, pdfUrl };
  } finally {
    if (browser) await browser.close();
  }
}

function buildPaperHtml(paper: IGeneratedPaper): string {
  const sectionsHtml = paper.sections
    .map(
      (section, sIdx) => `
      <div class="section">
        <h2>${section.title}</h2>
        <p class="instruction">${section.instruction}</p>
        <ol class="questions" start="${getStartNumber(paper, sIdx)}">
          ${section.questions
            .map(
              (q) => `
            <li class="question">
              <div class="q-header">
                <span class="q-text">${q.question}</span>
                <span class="q-marks">[${q.marks} marks]</span>
              </div>
              ${q.type === 'mcq' && q.options
                ? `<ul class="options">${q.options.map((o) => `<li><strong>${o.key}.</strong> ${o.text}</li>`).join('')}</ul>`
                : ''}
            </li>`
            )
            .join('')}
        </ol>
      </div>`
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Times New Roman', serif; font-size: 12pt; color: #000; margin: 0; padding: 0; }
  .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 12px; margin-bottom: 20px; }
  .school { font-size: 18pt; font-weight: bold; }
  .exam-title { font-size: 14pt; font-weight: bold; margin-top: 6px; }
  .meta { display: flex; justify-content: space-between; margin-top: 8px; font-size: 11pt; }
  .student-info { display: flex; gap: 30px; margin: 16px 0; border: 1px solid #ccc; padding: 10px; }
  .student-field { flex: 1; border-bottom: 1px solid #333; padding-bottom: 4px; }
  .section { margin-top: 24px; }
  h2 { font-size: 13pt; border-bottom: 1px solid #333; padding-bottom: 4px; }
  .instruction { font-style: italic; font-size: 11pt; margin-bottom: 12px; }
  .questions { padding-left: 20px; }
  .question { margin-bottom: 16px; }
  .q-header { display: flex; justify-content: space-between; }
  .q-text { flex: 1; }
  .q-marks { font-weight: bold; white-space: nowrap; margin-left: 10px; }
  .options { list-style: none; padding-left: 20px; margin-top: 6px; }
  .options li { margin-bottom: 4px; }
  .footer { position: fixed; bottom: 10mm; left: 0; right: 0; text-align: center; font-size: 9pt; color: #666; }
  @media print { .footer { position: fixed; } }
</style>
</head>
<body>
  <div class="header">
    <div class="school">VedaAI School</div>
    <div class="exam-title">${paper.title}</div>
    <div class="meta">
      <span>Total Marks: ${paper.totalMarks}</span>
      <span>Date: ${new Date(paper.generatedAt).toLocaleDateString()}</span>
    </div>
  </div>
  <div class="student-info">
    <div class="student-field">Name: ___________________________</div>
    <div class="student-field">Roll Number: __________</div>
    <div class="student-field">Section: __________</div>
  </div>
  ${sectionsHtml}
  <div class="footer">Generated by VedaAI | Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>
</body>
</html>`;
}

function getStartNumber(paper: IGeneratedPaper, sectionIndex: number): number {
  let total = 1;
  for (let i = 0; i < sectionIndex; i++) {
    total += paper.sections[i]?.questions.length ?? 0;
  }
  return total;
}
